version: '3'

services:
  chrome:
    build:
      context: .
      dockerfile: Dockerfile
    image: chrome-latest
    privileged: true  # Required for Chrome to work properly
    shm_size: '2gb'   # Increase shared memory size for better performance
    volumes:
      - ./output:/home/chrome/output  # Mount a directory for saving files
    command: --version  # Default command to show version
    # To override the command, use:
    # docker-compose run chrome --dump-dom https://www.google.com